- hosts: all
  gather_facts: yes
  become: yes
  
  vars:
    apache_vhost_filepath: "/etc/httpd/conf.d/vhosts.conf"

  tasks:
    - name: Hardening system
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Enable HTTP and HTTPS access
      firewalld:
        immediate: true
        permanent: true
        port: "{{ item }}/tcp"
        state: enabled
      loop:
        - 80
        - 443

    - name: Check if Apache vhost file exists
      stat:
        path: "{{ apache_vhost_filepath }}"
      register: vhost_filestat

    - name: Hardening Apache httpd
      lineinfile:
        path: "{{ apache_vhost_filepath }}"
        insertafter: '<VirtualHost'
        line: 'Redirect / https://server.local'
      notify:
        - reload_appache
      when: vhost_filestat.stat.exists | bool

  handlers:
    - name: reload_appache
      service:
        name: httpd
        state: reloaded
