# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "client_server" do |c|
    c.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end

    c.vm.box = "centos/7"
    c.vm.hostname = "server.local"
  end

  config.vm.define "awx" do |c|
    c.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end

    c.vm.box = "centos/7"
    c.vm.hostname = "awx.local"

    c.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
    end

  end
end
